geosolutions-it/geonode

geonode/layers/templates/layouts/panels.html

Initial metadata form reordering

---

geonode/layers/templates/layouts/panels.html
geonode/templates/metadata_form_js.html

- The attribute table is sortable by drag and drop
- Other minor fixes to the layout of steps (now are all similar)

Dataset Attributes sortable

---

geonode/templates/metadata_form_js.html

Add hints to proceed on optional fields

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/assets/css/risk.css
geonode/contrib/risks/client/index.html
geonode/contrib/risks/client/js/components/Chart.jsx
geonode/contrib/risks/client/js/components/ChartTooltip.jsx
geonode/contrib/risks/client/js/containers/DataContainer.jsx
geonode/contrib/risks/client/package.json

Added axis selection on bar click, improved tooltip and added Y axis values
Fixed css problem because of css name change

Charts improvements

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/assets/css/risk-disaster.less
geonode/contrib/risks/client/assets/css/risk.css
geonode/contrib/risks/client/js/components/AxesSelector.jsx
geonode/contrib/risks/client/js/components/Chart.jsx
geonode/contrib/risks/client/js/components/DownloadBtn.jsx
geonode/contrib/risks/client/js/components/Overview.jsx
geonode/contrib/risks/client/js/components/SwitchAdminU.jsx
geonode/contrib/risks/client/js/components/TopBar.jsx
geonode/contrib/risks/client/js/containers/DataContainer.jsx
geonode/contrib/risks/client/js/containers/MapContainer.jsx
geonode/contrib/risks/client/package.json

Fixed icons and style and Added Slider to map and charts

Fix #46 The number of available Analysis it not visible from the Overview and added slider to map and charts

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/assets/css/risk.css
geonode/contrib/risks/client/js/components/AxesSelector.jsx
geonode/contrib/risks/client/js/components/Overview.jsx

Fixed Added dimension on map slider and highlighted the analysis number

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/assets/css/variables.less
geonode/contrib/risks/client/js/components/TopBar.jsx
geonode/contrib/risks/client/js/epics/disaster.js
geonode/contrib/risks/client/js/utils/TutorialPresets.js
geonode/contrib/risks/client/localConfig.json

- Added rawSteps in Tutorial
- Fixed autostart issue
- Removed font path

Fixed #52 Tutorial general configuration and issues 

---

geonode/contrib/risks/client/assets/js/NotificationStyle.js
geonode/contrib/risks/client/js/components/DownloadData.jsx
geonode/contrib/risks/client/js/components/MoreInfo.jsx
geonode/contrib/risks/client/js/containers/DataContainer.jsx

Added download and more info buttons

Fix #34 At Risk Analysis level, allow to download the associated files

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/assets/css/disaster.less
geonode/contrib/risks/client/js/components/LayerBtn.jsx
geonode/contrib/risks/client/js/components/MoreInfo.jsx
geonode/contrib/risks/client/js/containers/MapContainer.jsx
geonode/contrib/risks/client/js/plugins/RiskTOC.js

Added more info list table and Fixed TOC style

---

geonode/contrib/risks/client/js/containers/DataContainer.jsx

Fix #90 [Disasterrisk] Icons for Analysis Types

---

geonode/contrib/risks/client/js/components/IdentifyBtn.jsx
geonode/contrib/risks/client/js/containers/MapContainer.jsx
geonode/contrib/risks/client/js/ms2Override/LeafletFeature.jsx
geonode/contrib/risks/client/js/plugins.js
geonode/contrib/risks/client/localConfig.json
geonode/contrib/risks/client/webpack.config.js

Fix #99 [Disasterrisk] Enable Get Feature Info on map

---

geonode/contrib/risks/client/js/components/SummaryChart.jsx
geonode/contrib/risks/client/js/containers/DataContainer.jsx

Fix #114 [Disasterrisk] Add a sumamry chart for all SSPs with lines below the bar chart

---

geonode/contrib/risks/client/assets/css/bootstrap.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/js/actions/disaster.js
geonode/contrib/risks/client/js/components/AdditionalChart.jsx
geonode/contrib/risks/client/js/containers/CostDataContainer.jsx
geonode/contrib/risks/client/js/reducers/disaster.js
geonode/contrib/risks/client/js/selectors/disaster.js
geonode/contrib/risks/client/webpack.config.js

Fix #136 [Disasterrisk] [SPIKE] Additional Section / Tables Data JSON

---

geonode/contrib/risks/client/js/actions/disaster.js
geonode/contrib/risks/client/js/components/MenuScenario.jsx
geonode/contrib/risks/client/js/components/SwitchChartBtn.jsx
geonode/contrib/risks/client/js/containers/CostDataContainer.jsx
geonode/contrib/risks/client/js/containers/CostsMapContainer.jsx
geonode/contrib/risks/client/js/reducers/disaster.js
geonode/contrib/risks/client/js/selectors/disaster.js
geonode/contrib/risks/client/js/utils/TutorialPresets.js

Included only in Cost/benefit
to do Risk Analysis

[Disasterrisk] Fix #171 Include extra details for resources associated to dimension values

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/assets/css/variables.less
geonode/contrib/risks/client/assets/translations/data.de-DE
geonode/contrib/risks/client/assets/translations/data.en-US
geonode/contrib/risks/client/assets/translations/data.fr-FR
geonode/contrib/risks/client/assets/translations/data.it-IT
geonode/contrib/risks/client/js/components/AdditionalChart.jsx
geonode/contrib/risks/client/js/components/MenuScenario.jsx
geonode/contrib/risks/client/js/components/SliderChart.jsx
geonode/contrib/risks/client/js/containers/CostDataContainer.jsx
geonode/contrib/risks/client/js/utils/TutorialPresets.js

Modified cost/benefit page layout and styles

Fix #171 [Disasterrisk] Include extra details for resources associated to dimension values

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/js/components/MenuScenario.jsx
geonode/contrib/risks/client/js/containers/CostDataContainer.jsx
geonode/contrib/risks/client/js/containers/CostsMapContainer.jsx
geonode/contrib/risks/client/package.json

* Fixed panel style issue
* Fixed resource error when missing

[Disasterrisk] Added HTML support on hazard purpose and scenario abstract (Cost/Benefit)

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/js/components/AxesSelector.jsx
geonode/contrib/risks/client/js/components/LabelResource.jsx
geonode/contrib/risks/client/js/components/ShareLink.jsx
geonode/contrib/risks/client/js/components/SummaryChart.jsx
geonode/contrib/risks/client/js/components/TopBar.jsx
geonode/contrib/risks/client/js/containers/CostDataContainer.jsx
geonode/contrib/risks/client/js/containers/RiskDataContainer.jsx
geonode/contrib/risks/client/js/reducers/disaster.js

[Disasterrisk] Fixed risk ui and buttons displacement

---

geonode/contrib/risks/client/assets/css/common.less
geonode/contrib/risks/client/assets/css/disaster.css
geonode/contrib/risks/client/js/actions/disaster.js
geonode/contrib/risks/client/js/components/AdditionalChart.jsx
geonode/contrib/risks/client/js/reducers/disaster.js
geonode/contrib/risks/client/js/selectors/disaster.js

[Disasterrisk] Added multiple additional charts cost/benefit

---

geonode/contrib/risks/client/js/components/SummaryChart.jsx

[Disasterrisk] Added AED bar chart (risk application)

---

geonode/settings.py

Reverts geosolutions-it/geonode#281

Revert "fixed invalid datetime_input_formats addition"

---

geonode/contrib/monitoring/aggregation.py
geonode/contrib/monitoring/collector.py
geonode/contrib/monitoring/management/commands/aggregate_metrics.py
geonode/contrib/monitoring/models.py
geonode/contrib/monitoring/tests.py
geonode/contrib/monitoring/utils.py
geonode/settings.py

User analytics aggregation

---

geonode/storage/aws.py
geonode/storage/dropbox.py
geonode/storage/gcs.py
geonode/storage/tests.py
requirements.txt
setup.cfg

Base implementation of cloud storages for dropbox, gcs and aws

[Issue #126] base implementation of storages based on django-storages

---

geonode/layers/management/commands/importlayers.py

Add helper if no path are provided, add get to make the import processed

---

geonode/layers/utils.py
geonode/layers/views.py
geonode/resource/manager.py
geonode/resource/utils.py

Generalization of update method, rename gs_resource and fix regiorns

Generalization of update method, rename gs_resource and fix regiorns

---

geonode/base/forms.py
geonode/resource/utils.py

Geostory metadata error

---

geonode/layers/tests.py
geonode/maps/api/hook.py
geonode/resource/utils.py

Minor bugfix for maps and resource update

---

geonode/geoapps/api/tests.py

Fix failing test

---

geonode/layers/tests.py
geonode/layers/views.py
geonode/upload/upload.py

Missing changes from 7693

---

geonode/client/hooksets.py
geonode/client/templatetags/client_lib_tags.py
geonode/documents/templates/documents/document_metadata_advanced.html
geonode/documents/templates/documents/document_thumb_upload.html
geonode/documents/templates/documents/document_upload_base.html
geonode/geoapps/templates/apps/app_metadata_advanced.html
geonode/geoserver/createlayer/templates/createlayer/layer_create.html
geonode/layers/templates/layers/layer_append.html
geonode/layers/templates/layers/layer_granule_remove.html
geonode/layers/templates/layers/layer_metadata.html
geonode/layers/templates/layers/layer_metadata_advanced.html
geonode/layers/templates/layers/layer_metadata_upload.html
geonode/layers/templates/layers/layer_remove.html
geonode/layers/templates/layers/layer_replace.html
geonode/layers/templates/layers/layer_style_upload.html
geonode/layers/templates/upload/layer_upload.html
geonode/layers/templates/upload/layer_upload_base.html
geonode/layers/templates/upload/layer_upload_metadata_base.html
geonode/maps/templates/maps/map_metadata_advanced.html
geonode/services/templates/services/services_base.html
geonode/templates/500.html
geonode/templates/base.html
geonode/templates/index.html
geonode/templates/metadata_detail.html

[Fixes #252] Change button links to reference the new editors

---

geonode/client/hooksets.py
geonode/geoserver/helpers.py
geonode/geoserver/manager.py
geonode/geoserver/tasks.py
geonode/geoserver/tests/test_manager.py
geonode/layers/models.py
geonode/layers/views.py
geonode/resource/manager.py
geonode/resource/utils.py
geonode/upload/files.py
geonode/upload/upload.py
geonode/upload/views.py

The method allows to create a resource by providing the list of files.
e.g.:
```python
In [1]: from geonode.resource.manager import resource_manager
In [2]: from geonode.layers.models import Layer
In [3]: from django.contrib.auth import get_user_model
In [4]: admin = get_user_model().objects.get(username='admin')
In [5]: files = ["/.../san_andres_y_providencia_administrative.dbf", "/.../san_andres_y_providencia_administrative.prj",
...:  "/.../san_andres_y_providencia_administrative.shx", "/.../san_andres_y_providencia_administrative.sld", "/.../san_andres_y_providencia_administrative.shp"]
In [6]: resource_manager.ingest(files, resource_type=Layer, defaults={'owner': admin})
```

[Resource Manager] Ingest method
